### ISSUE TITLE
Take time to load again when I tap an emoji.

### ISSUE THREAD

**Issue by imAunAbbas** [i-Naji/emoji_keyboard#1]
--> It is a very annoying behavior when I tap an emoji, it takes some milliseconds to load the emojis again and shows a blank screen during loading whenever I use `setState(() {});`. This is not a good approach as many people try many emojis by quickly tapping them, but if it will show blank screen to load emojis again then users will not use this.

--> Secondly, then documentation is not fully explaining all the properties and functionalities.

Kindly help me on these issues. Thanks

**Comment by i-Naji** [comment]
Use a key for the keyboard to avoid rebuilding on setState. (or use other [state management systems](https://flutter.dev/docs/development/data-and-backend/state-mgmt/options), keyboard widget contains over 3000 emojis and is costly to rebuild)
Pls, Take look at [EmojiKeyboard documention](https://pub.dev/documentation/flutter_emoji_keyboard/latest/flutter_emoji_keyboard/EmojiKeyboard/EmojiKeyboard.html) If in doubt feel free to ask any questions.

**Comment by imAunAbbas** [comment]
Thanks for your help 👍🏻. Actually I'm using a callback that is returning the value `emoji.text` and that value is adding in the `TextField`'s text. And I'm using `setState` to add that emoji in that text. That's why when `EmojiKeyboard` is active, it blinks (for loading all emojis) when I select any emoji. So in this scenario, `key` property on `EmojiKeyboard` is also not working. That's why I'm moving towards state management for this issue.

**Comment by i-Naji** [comment]
I see. you can simply use TextEditingController as used in [example](https://github.com/i-Naji/emoji_keyboard/blob/658c2d7b95cd36546a6fff17c35b7323264838a2/example/lib/main.dart#L22)

**Comment by imAunAbbas** [comment]
Thank you so much, it's working fine with `TextEditingController`.
