### ISSUE TITLE
App crashes (gives error) when try to open emoji_keyboard

### ISSUE THREAD

**Issue by imAunAbbas** [i-Naji/emoji_keyboard#4]
I'm using this keyboard for a few months but with the new `Flutter` release, this keyboard stopped working and gives error while trying to open it.
It gives the error on `_EmojiKeyboardHeader` class in `emoji_keyboard_widget.dart` file. According to flutter fixes when I try to add the following lines of code, it still gives the same error.

```
@override
  // TODO: implement showOnScreenConfiguration
  PersistentHeaderShowOnScreenConfiguration get showOnScreenConfiguration =>
      throw UnimplementedError();

  @override
  // TODO: implement vsync
  TickerProvider get vsync => throw UnimplementedError();
```

The issue is not resolved even when I remove `TODO` hints or add `ignore` on these methods.

Flutter also gives another option to overcome this problem to add this instead:

```
@override
  dynamic noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
```

But this is also not working. My Flutter version is `1.22.2`, kindly help me solve this problem. Thanks

**Comment by jenniestrongbow** [comment]
Same problem.

**Comment by imAunAbbas** [comment]
@i-Naji have you found any solution of this?
